spring:
  datasource:
    url: jdbc:mysql://shoaib:Shoaib123@localhost:3306/security_demo
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true
jwt:
  signing-key-secret: 28482B4D6251655468576D5A7134743677397A24432646294A404E635266556A